// DECLARANDO QUAL PINO RECEBERÁ O VALOR COLETADO PELO SENSOR
const int PINO_SENSOR_UMIDADE_SOLO = A5;

void setup()
{
  // DECLARANDO A FREQUÊNCIA DE ATUALIZAÇÃO DE BITS
  Serial.begin(9600);
  // DECLARANDO O TIPO DE ATIVIDADE DO PINO (INPUT)
  pinMode(PINO_SENSOR_UMIDADE_SOLO, INPUT);
}

void loop()
{
  // DECLARANDO A VARIÁVEL QUE RECEBE O VALOR COLETADO PELO SENSOR DE UMIDADE
  int leituraSensor = analogRead(PINO_SENSOR_UMIDADE_SOLO);

  /*
  DECLARANDO A VARIÁVEL QUE CONVERTE DO VALOR RECEBIDO DO SENSOR, DE BYTE PARA MEGABYTE,
  DEPOIS MULTIPLICANDO POR 100 PARA MOSTRAR O RESULTADO EM PORCENTAGEM
  */
  float porcentagemUmidade = 100 - ((leituraSensor / 1023.0) * 100);

  /*
  MOSTRA NO CONSOLE "Umidade do Solo:", MOSTRA O VALOR DA PORCENTAGEM + " %"
  */
  Serial.print("Umidade do Solo: ");
  Serial.print(porcentagemUmidade);
  Serial.println(" %");

  // AGUARDA 1 SEGUNDO PARA EXECUTAR OS COMANDOS DENTRO DO LOOP NOVAMENTE
  delay(1000);
}
